name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
family: "llama"
mode: "prompt"

# 토크나이저 설정
tokenizer:
  max_length: 2048
  padding_side: "left"
  truncation_side: "left"

# 모델 설정
model:
  trust_remote_code: true
  torch_dtype: "float16"
  device_map: "auto"

# 생성 설정을 최상위로 이동
generation:
  max_new_tokens: 128
  temperature: 0.3
  top_p: 0.95
  do_sample: true
  num_beams: 5
  length_penalty: 1.0

# 양자화 설정 (finetune 모드용)
quantization:
  enabled: true
  precision: "int4"
  compute_dtype: "float16"

# LoRA 설정 (finetune 모드용)
lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj"]
 