name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
family: "llama"
mode: "prompt"

# 토크나이저 설정
tokenizer:
  max_length: 2048
  padding_side: "left"
  truncation_side: "left"

# 모델 설정
model:
  trust_remote_code: true
  torch_dtype: "float16"
  device_map: "auto"

# 생성 설정을 최상위로 이동
generation:
  max_new_tokens: 32
  min_length: 10
  temperature: 0.3
  top_p: 0.7
  repetition_penalty: 2.5
  no_repeat_ngram_size: 5
  early_stopping: true
  do_sample: true
  num_beams: 5
  length_penalty: 0.6
  eos_token_id: 2
  pad_token_id: 2
  bad_words: [
    "Summary:", "summary:", "요약:", "Dialogue:", "dialogue:", "대화:",
    "Person1", "Person2", "The", "In", "This", "It", "They", "We", "You"
  ]

# 양자화 설정 (finetune 모드용)
quantization:
  enabled: true
  precision: "int4"
  compute_dtype: "float16"

# LoRA 설정 (finetune 모드용)
lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj"]
 