name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
family: "llama"
mode: "finetune"

# 토크나이저 설정
tokenizer:
  max_length: 1024
  padding_side: "left"
  truncation_side: "left"

# 모델 설정
model:
  trust_remote_code: true
  torch_dtype: "float16"
  device_map: "auto"

# 생성 설정을 최상위로 이동
generation:
  max_new_tokens: 128
  temperature: 0.3
  top_p: 0.95
  do_sample: true
  num_beams: 5
  length_penalty: 1.0

# 양자화 설정 강화
quantization:
  enabled: true
  precision: "int4"
  compute_dtype: "float16"
  double_quant: true
  quant_type: "nf4"

# LoRA 설정 최적화
lora:
  r: 4
  alpha: 16
  dropout: 0.1
  target_modules: [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj"
  ]

# 학습 설정 최적화
train:
  training:
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 8
    gradient_checkpointing: true
    fp16: true
    bf16: false
    max_grad_norm: 1.0
    optim: "paged_adamw_8bit"
 