name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
family: "llama"
type: "prompt"
mode: "prompt"
# 토크나이저 설정
tokenizer:
  max_length: 2048
  padding_side: "left"
  truncation_side: "left"

# 모델 설정
model:
  trust_remote_code: true
  torch_dtype: "float16"
  device_map: "auto"
  # 생성 설정
  generation:
    max_new_tokens: 256
    temperature: 0.6
    top_p: 0.9
    repetition_penalty: 1.3
    no_repeat_ngram_size: 3
    early_stopping: true

# 양자화 설정 (finetune 모드용)
quantization:
  enabled: true
  precision: "int4"
  compute_dtype: "float16"

# LoRA 설정 (finetune 모드용)
lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj"]

# 프롬프트 템플릿 설정
prompt_templates:
  v1:
    system: |
      You are an expert Korean dialogue summarizer. Follow these rules:
      1. Summarize the dialogue concisely in Korean
      2. Focus only on key points
      3. Do not add any explanations after the summary
      4. Do not translate to English
      당신은 한국어 대화 요약 전문가입니다. 다음 규칙을 따르세요:
      1. 대화를 한국어로 간단히 요약하세요
      2. 핵심 내용만 포함하세요
      3. 요약 후 추가 설명을 하지 마세요
      4. 영어로 번역하지 마세요
    few_shot: |
      Example Dialogue: {sample_dialogue}
      Example Summary: {sample_summary}

      Now summarize this dialogue:
      Dialogue: {dialogue}
      Summary:
    zero_shot: |
      Dialogue: {dialogue}
      Summary: 