name: "gogamza/kobart-summarization"
family: "bart"
mode: "prompt"

tokenizer:
  max_length: 2048
  padding_side: "left"
  truncation_side: "left"
  encoder_max_len: 1024
  decoder_max_len: 128

model:
  trust_remote_code: true
  torch_dtype: "float16"
  device_map: "auto"

generation:
  max_new_tokens: 48
  min_length: 10
  temperature: 0.2
  top_p: 0.9
  repetition_penalty: 3.0
  no_repeat_ngram_size: 6
  early_stopping: true
  do_sample: true
  num_beams: 3
  length_penalty: 0.8
  stop_sequences: ["###", "대화", "Summary:", "Dialogue:"]
  bad_words: [
    "Person1", "Person2", "The", "In", "This",
    "assistant", "Assistant", "Summary", "대화", "요약"
  ] 