name: "gogamza/kobart-summarization"
mode: "finetune"
family: "bart"

tokenizer:
  max_length: 1024
  padding: "max_length"
  truncation: true
  return_tensors: "pt"

generation:
  num_beams: 4
  max_length: 256
  min_length: 32
  length_penalty: 1.0
  early_stopping: true 