name: "gogamza/kobart-base-v2"
type: "finetune"

tokenizer:
  bos_token: "<s>"
  eos_token: "</s>"
  decoder_max_len: 128
  encoder_max_len: 512
  special_tokens:
    additional_special_tokens:
      - "#Person1#"
      - "#Person2#"
      - "#Person3#"
      - "#PhoneNumber#"
      - "#Address#"
      - "#PassportNumber#" 