name: "gogamza/kobart-summarization"
family: "bart"
mode: "prompt"

tokenizer:
  max_length: 2048
  padding_side: "left"
  truncation_side: "left"
  encoder_max_len: 1024
  decoder_max_len: 128

model:
  trust_remote_code: true
  torch_dtype: "float16"
  device_map: "auto"

generation:
  max_new_tokens: 64
  min_length: 10
  temperature: 0.3
  top_p: 0.9
  repetition_penalty: 1.2
  no_repeat_ngram_size: 3
  early_stopping: true
  do_sample: true
  num_beams: 5
  length_penalty: 1.0 