name: "solar-1-mini-chat"
mode: "prompt"
family: "solar"

# API 설정
api:
  base_url: "https://api.upstage.ai/v1/solar"
  api_key: ${oc.env:UPSTAGE_API_KEY}
  model: "solar-1-mini-chat"

# 생성 설정
generation:
  num_beams: 5
  max_new_tokens: 200  # 200자 * 3토큰
  min_new_tokens: 50   # 50자 * 3토큰
  length_penalty: 1.0
  repetition_penalty: 1.2
  no_repeat_ngram_size: 3
  early_stopping: true
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  do_sample: true
  stop_sequences: ["###", "대화", "Summary:", "Dialogue:"]

tokenizer:
  max_length: 2048
  padding: "max_length"
  truncation: true
  return_tensors: "pt"
  encoder_max_len: 2048
  decoder_max_len: 200
