name: "solar/solar-1.0"
family: "solar"
mode: "prompt"

# API 설정
api:
  base_url: "https://api.upstage.ai/v1/solar"
  api_key: ${oc.env:UPSTAGE_API_KEY}
  temperature: 0.7
  top_p: 0.9

# 프롬프트 템플릿 설정
prompt_templates:
  v1:
    system: |
      You are a expert in the field of dialogue summarization, summarize the given dialogue in a concise manner. Follow the user's instruction carefully and provide a summary that is relevant to the dialogue.
    few_shot: |
      Following the instructions below, summarize the given document.
      Instructions:
      1. Read the provided sample dialogue and corresponding summary.
      2. Read the dialogue carefully.
      3. Following the sample's style of summary, provide a concise summary of the given dialogue.

      Sample Dialogue:
      {sample_dialogue}

      Sample Summary:
      {sample_summary}

      Dialogue:
      {dialogue}

      Summary:
    zero_shot: |
      Summarize the following dialogue:
      Dialogue: {dialogue}
      Summary:
  v2:
    system: |
      You are a expert in the field of dialogue summarization, summarize the given dialogue in a concise manner. Follow the user's instruction carefully and provide a summary that is relevant to the dialogue.
    instruction: |
      Following the instructions below, summarize the given document.
      Instructions:
      1. Read the provided sample dialogue and corresponding summary.
      2. Read the dialogue carefully.
      3. Following the sample's style of summary, provide a concise summary of the given dialogue. Be sure that the summary is simple but captures the essence of the dialogue.
    few_shot:
      user: |
        {instruction}
        Dialogue:
        {sample_dialogue}

        Summary:
      assistant: "{sample_summary}"
      final_user: |
        Dialogue:
        {dialogue}

        Summary:
    zero_shot: |
      Summarize the following dialogue:
      Dialogue: {dialogue}
      Summary:
