name: "solar-api"  # wandb 로깅용
family: "solar"
mode: "prompt"

# API 설정
api:
  base_url: "https://api.upstage.ai/v1/solar"
  api_key: ${oc.env:UPSTAGE_API_KEY}
  model: "solar-1-mini-chat"

# 생성 설정
generation:
  max_new_tokens: 64
  temperature: 0.2
  top_p: 0.95
  stop_sequences: ["###", "대화", "Summary:", "Dialogue:"]
