name: "solar/solar-1.0"
family: "solar"
mode: "prompt"

# API 설정
api:
  base_url: "https://api.upstage.ai/v1/solar"
  api_key: ${oc.env:UPSTAGE_API_KEY}
  temperature: 0.2
  top_p: 0.9
  generation:
    max_tokens: 64  # max_tokens만 유지
    stop: ["<s>", "</s>", "<pad>"]  # stop 토큰만 유지
