# defaults:
#   - ../common  # common.yaml 참조

name: "eenzeenee/t5-base-korean-summarization"
mode: "finetune"
family: "t5"

# 모델 특화 설정

partial_training: true
num_layers_to_train: 2
lora: false
quantization:
  enabled: false
  precision: "int8"
  compute_dtype: "float16"
tokenizer:
  max_length: 512
  padding: "max_length"
  truncation: true
  return_tensors: "pt"
  encoder_max_len: 512
  decoder_max_len: 200
  bos_token: "<s>"
  eos_token: "</s>"
  special_tokens:
    additional_special_tokens: ${common.additional_special_tokens}  # 참조 방식 수정

generation:
  num_beams: 5
  max_new_tokens: 200  # 200자 * 3토큰
  min_new_tokens: 50   # 50자 * 3토큰
  length_penalty: 1.0
  repetition_penalty: 1.2
  no_repeat_ngram_size: 3
  early_stopping: true
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  do_sample: true