name: "eenzeenee/t5-base-korean-summarization"
mode: "finetune"
family: "t5"

# 모델 특화 설정

partial_training: true
num_layers_to_train: 2
lora: false
quantization:
  enabled: false
  precision: "int8"
  compute_dtype: "float16"
tokenizer:
  max_length: 1024
  padding: "max_length"
  truncation: true
  return_tensors: "pt"
  encoder_max_len: 1024
  decoder_max_len: 128

generation:
  num_beams: 4
  max_length: 256
  min_length: 32
  length_penalty: 1.0
  repetition_penalty: 1.2
  no_repeat_ngram_size: 3
  early_stopping: true
  max_new_tokens: 128
  min_new_tokens: 10
  temperature: 0.7
  top_p: 0.9
  do_sample: true
