name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=2.1.4
  - numpy=1.23.5
  - tqdm
  - jupyter
  - jupyterlab
  - python-dotenv
  - pip:
    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
    - hydra-core==1.3.0
    - openai
    - wandb==0.16.1
    - pytorch-lightning==2.1.2
    - transformers[torch]==4.35.2
    - rouge==1.0.1
    - wget==3.2
    - peft==0.4.0
    - datasets>=2.0.0 