name: nlp
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8
  - pandas=2.1.4
  - numpy=1.23.5
  - tqdm=4.66.1
  - jupyter=1.0.0
  - jupyterlab=4.0.9
  - python-dotenv=1.0.0
  - pip:
    - hydra-core==1.3.0
    - openai
    - wandb==0.16.1
    - pytorch-lightning==2.1.2
    - transformers[torch]==4.35.2
    - rouge==1.0.1
    - wget==3.2
    - peft==0.4.0
    - datasets>=2.0.0 