# 기본 학습 설정
training:
  # 기본 학습 설정
  num_train_epochs: 10
  learning_rate: 2e-4
  warmup_ratio: 0.1
  weight_decay: 0.01
  max_grad_norm: 1.0
  optim: "paged_adamw_8bit"
  
  # 배치 및 메모리 최적화
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  
  # 하드웨어 최적화
  fp16: false
  bf16: true
  
  # 평가 및 저장 전략
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  load_best_model_at_end: true
  metric_for_best_model: "eval/rouge1_f1"
  greater_is_better: true
  
  # 로깅
  logging_steps: 10
  logging_first_step: true
  logging_dir: "${general.output_path}/logs"
  
  # 생성 관련
  predict_with_generate: true
  remove_unused_columns: true
  generation_max_length: ${model.generation.max_new_tokens}
  generation_num_beams: ${model.generation.num_beams}

inference:
  batch_size: 32
  max_length: 100
  num_beams: 4
  no_repeat_ngram_size: 2
  early_stopping: true
  remove_tokens:
    - <usr>
    - <s>
    - </s>
    - <pad> 